export const majorsData = [
  { name: 'Computer Science' },
  { name: 'Software Development' },
  { name: 'Software Engineering' },
  { name: 'Cybersecurity' },
  { name: 'Information Technology' },
  { name: 'Data Analytics' },
  { name: 'Data Science' },
  { name: 'Artificial Intelligence' },
  { name: 'Digital Infrastructure' },
  { name: 'Interactive App Design and Development' },
  { name: 'Information and Communications Technology' },
  { name: 'Computer Networking' },
  { name: 'Network Engineering' },
  { name: 'IT Project Management' },
  { name: 'Database & Programming' },
  { name: 'Cloud Computing' },
  { name: 'Network Security' },
  { name: 'DevOps and Cloud Infrastructure' },
  { name: 'Robotics and Automation Engineering' },
  { name: 'Computer Engineering' },
  { name: 'Electronics and Telecommunications' },
  { name: 'Mobile Application Development' },
  { name: 'Web Development' },
  { name: 'Augmented / Virtual Reality (AR/VR) Applications' },
];